language: php

php:
  - 7.1
  - 7.2

before_script:
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - cp .env.testing .env

script:
  - vendor/bin/phpunit
