language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan config:cache

script:
  - vendor/bin/phpunit
